### ISSUE TITLE
VOXEL: Alpha channel support should be added.

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#213]
voxedit would need an option in the palette panel, too (to edit the alpha channel)

editing the alpha channel in the palette panel is of course not enough then - we also have to render the alpha voxels. Therefore the  `CubicSurfaceExtractor.h` must extract all solid voxels - followed by the unsolid voxels into two different meshes. The second mesh (alpha) must then be sorted in regards to the camera position and rendered last.

# TODO:
* [x] Alpha support for the palette panel
* [x] `VoxelType` has to be updated if alpha value in a palette was changed
* [x] Mesh extractors have to extract two meshes
* [x] Mesh formats have to export the transparent mesh, too
* [x] `fillHollow` has to take `VoxelType::Transparent` into account

**Comment by mgerhardy** [comment]
this is related to #126

**Comment by mgerhardy** [comment]
`ImGuiColorEditFlags_NoAlpha` should be removed from the palette panel
